name: NuGet Publishing

on:
  #push:
  #  branches: [ master ]
  #  paths: [ TPLinkSmartDevice.NETCore/TPLinkSmartDevice.NETCore.csproj ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Publish
      - name: Publish Package on Version Change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: TPLinkSmartDevice.NETCore/TPLinkSmartDevice.NETCore.csproj
          PACKAGE_NAME: TPLinkSmartDevice.NETCore
          
          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          # VERSION_FILE_PATH: Directory.Build.props

          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$

          # Format of the git tag, [*] gets replaced with actual version
          TAG_FORMAT: v*

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
